name: Make NikiCMD

on:
  workflow_dispatch:  # Allows you to manually trigger it

jobs:
  build-project:
    name: Build Project
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Project
        uses: actions/checkout@v4.2.2

      - name: Build Project
        uses: threeal/cmake-action@v2.1.0
        with:
            generator: Unix Makefiles
            source-dir: cpp_program
            build-dir: cpp_program/build
            options: |
                CMAKE_BUILD_TYPE=Release

      - name: Move to root
        run: mv cpp_program/build/NikiCMD ./NikiCMD

      - name: Commit and push executable
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add NikiCMD
          git commit -m "Update NikiCMD"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
