name: Run Discord Bot

on:
  workflow_dispatch:  # Allows you to manually trigger it

jobs:
  run-bot:
    environment: bot
    runs-on: ubuntu-latest  # Use Linux for lightweight execution
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Make script executable
        run: chmod +x NikiCMD  # Change filename as needed

      - name: Run bot
        env:
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}  # Use GitHub Secret for safety
          DISCORD_BOT_OWNERS: ${{ secrets.DISCORD_BOT_OWNERS }}
        run: python bot.py
