name: Run Discord Bot

on:
  push:
    branches:
      - main  # Change to your branch name if needed
  workflow_dispatch:  # Allows you to manually trigger it

jobs:
  run-bot:
    runs-on: ubuntu-latest  # Use Linux for lightweight execution
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install discord.py

      - name: Run bot
        env:
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}  # Use GitHub Secret for safety
        run: python bot.py
